networks:
  gitea-network:
    external: false

services:
  gitea-server:
    image: docker.gitea.com/gitea:1.23.8
    container_name: docker-compose-gitea
    environment:
      - USER_UID=1001
      - USER_GID=1001
      #- GITEA__server__ROOT_URL=http://gitea.lan/
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=gitea-db:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    restart: unless-stopped
    networks:
      - gitea-network
    volumes:
      - ./data/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /home/git/.ssh/:/data/git/.ssh
    ports:
      - "3000:3000"
      - "222:22"
      - "127.0.0.1:2222:22"
    depends_on:
      - gitea-db
 
  gitea-db:
    image: docker.io/library/mysql:8
    container_name: docker-compose-gitea-mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
    networks:
      - gitea-network
    volumes:
      - ./data/mysql:/var/lib/mysql

